name: Deploy tooch-town stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy stack
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DOCKER_HUB_USERNAME,DOCKER_HUB_TOKEN
          script: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
            cd /home/libetti/deploy-tooch-town
            git checkout main
            docker compose pull
            docker compose up -d
            docker image prune -f
